# Generated by Django 5.2.1 on 2025-05-14 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('household', 'Побутова техніка'), ('computer', "Комп'ютерна техніка"), ('smartphones', 'Смартфони'), ('other', 'Інше')], max_length=20)),
                ('subcategory', models.CharField(choices=[('fridges', 'Холодильники'), ('washing_machines', 'Пральні машини'), ('boilers', 'Бойлери'), ('ovens', 'Печі'), ('hoods', 'Витяжки'), ('microwaves', 'Мікрохвильові печі'), ('pc', 'ПК'), ('laptops', 'Ноутбуки'), ('monitors', 'Монітори'), ('printers', 'Принтери'), ('scanners', 'Сканери'), ('android', 'Android смартфони'), ('ios', 'iOS/Apple смартфони'), ('clothes', 'Одяг'), ('shoes', 'Взуття'), ('accessories', 'Аксесуари'), ('sport', 'Спортивне обладнання'), ('toys', 'Іграшки')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Активне'), ('inactive', 'Неактивне')], default='active', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
